config/routes.rb
Rails.application.routes.draw do
  # User routes
  resources :users
  
  # Session routes for login and logout
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # Task routes
  resources :tasks do
    member do
      get 'manual_delete'
    end
  end

  # Set the root route
  root 'sessions#new'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    attr_accessor :unschedulable
    validates :name, presence: { message: "can't be blank" }
    validates :description, presence: { message: "can't be blank" }
    enum difficulty: { low: 1, medium: 2, high: 3, urgent: 4 }
    validates :estimate, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 200 }, presence: true


    # Callback to set duration before validation (so it is set when the task is created or updated)
    before_validation :set_duration
    #before_validation :calculate_start_time
    before_validation do
        calculate_start_time(5)
    end

    # Private method to calculate and set the duration
    def set_duration
        difficulty_value = Task.difficulties[self.difficulty] || 0
  
        self.duration = 2 * difficulty_value + self.estimate
    end

    scope :ordered_by_duration, -> { order(duration: :desc) }

    def calculate_start_time(work_hours_per_day)
        return if due_date.nil?
        workday_start_hour = 9 
        workday_end_hour = 14
    
        current_time = Time.current
        days_before_due_to_start = (duration / (workday_end_hour - workday_start_hour)).ceil
        start_time = due_date - days_before_due_to_start
    
        # no time to finish
        if start_time < current_time
            # start_time = nil
            start_time = current_time
        end
    
        # Save the calculated start time in an attribute
        self.start_time = start_time
      end
end
  
  

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :tasks
    before_save { email.downcase! }
    validates :email, presence: true, uniqueness: { case_sensitive: false }
    validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
      @user = User.new
    end
  
    def create
      user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
        # Log the user in
        log_in user
        redirect_to tasks_path
      else
        # Create an error message and re-render the signin form
        flash.now[:login_error] = "Invalid email or password."
        render 'new'
      end

    end
  
    def destroy
      log_out if logged_in?
      redirect_to root_url
    end
  
    private
  
    # Log in the given user
    def log_in(user)
      session[:user_id] = user.id
    end
  
    # Returns true if the user is logged in, false otherwise
    def logged_in?
      !session[:user_id].nil?
    end
  
  end

app/controllers/tasks_controller.rb
# class TasksController < ApplicationController
#   before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy, :manual_delete]

#   # Get all tasks
#   def index
#     sort_column = params[:sort] || 'name'
#     sort_direction = params[:direction] || 'asc'

#     sort_column = 'name' unless Task.column_names.include?(sort_column)
#     sort_direction = 'asc' unless %w[asc desc].include?(sort_direction)

#     @tasks = Task.all.order(sort_column + ' ' + sort_direction)
#   end


#   # Show form for a new task
#   def new
#     @task = Task.new
#   end

#   # Create a new task
#   def create
#     @task = Task.new(task_params)
#     if @task.save      
#         redirect_to tasks_path, notice: 'Task was successfully created.'
#     else
#       flash.now[:alert] = @task.errors.full_messages.to_sentence
#       render :new
#     end
#   end


#   #Show a single task
#   def show
#     @task = Task.find(params[:id])
#   end

#   # Show form for editing a task
#   def edit
#     @task = Task.find(params[:id])
#   end

#   # Update a task
#   def update
#        @task = Task.find(params[:id])
#     if @task.update(task_params)
#       # @task.calculate_start_time(5)
#       redirect_to tasks_path, notice: 'Task was successfully updated.'
#     else
#       flash.now[:alert] = @task.errors.full_messages.to_sentence
#       render :edit
#     end
#   end


#   def manual_delete
#     @task = Task.find(params[:id])
#     @task.destroy
#     redirect_to tasks_path, notice: 'Task was successfully deleted.'
#   end
#   # Delete a task
#   # def destroy
#   #   @task = Task.find(params[:id])
#   #   @task.destroy
#   #   redirect_to tasks_path, notice: 'Task was successfully deleted.'
#   # end    

#   private
#   # Define strong parameters for the Task model
#   def task_params
#     params.require(:task).permit(:name, :description, :due_date, :difficulty, :estimate)
#   end
  
# end
class TasksController < ApplicationController
  before_action :authenticate_user
  before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy, :manual_delete]

  # Get all tasks
  def index
      sort_column = params[:sort] || 'name'
      sort_direction = params[:direction] || 'asc'
    
      sort_column = 'name' unless Task.column_names.include?(sort_column)
      sort_direction = 'asc' unless %w[asc desc].include?(sort_direction)
    
      @tasks = current_user.tasks.order("#{sort_column} #{sort_direction}")
  end


  def new
      @task = current_user.tasks.build
  end
  
  # Create a new task
  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      redirect_to tasks_path, notice: 'Task was successfully created.'
    else
      flash.now[:alert] = @task.errors.full_messages.to_sentence
      render :new
    end
  end


  #Show a single task
  def show
    @task = current_user.tasks.find(params[:id])
  end

  # Show form for editing a task
  def edit
    @task = current_user.tasks.find(params[:id])
  end

  # Update a task
  def update
       @task = current_user.tasks.find(params[:id])
    if @task.update(task_params)
      # @task.calculate_start_time(5)
      redirect_to tasks_path, notice: 'Task was successfully updated.'
    else
      flash.now[:alert] = @task.errors.full_messages.to_sentence
      render :edit
    end
  end


  def manual_delete
    @task = current_user.tasks.find(params[:id])
    @task.destroy
    redirect_to tasks_path, notice: 'Task was successfully deleted.'
  end 

  private

  def task_params
    params.require(:task).permit(:name, :description, :due_date, :difficulty, :estimate)
  end

  def logged_in_user
    redirect_to login_url unless current_user
  end

  def authenticate_user
    redirect_to login_path, alert: "You must be logged in to access this page." if current_user.nil?
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
      @user = User.new
    end
  
    def create
      puts user_params
      @user = User.new(user_params)
      if @user.save
        # Redirect to task page
        redirect_to login_path, notice: 'Successfully signed up! Please log in.'
      else
        render :new  
      end
    end
  
    private
  
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
    # def priority_color(priority)
    #     case priority
    #     when 1..2
    #       'red'
    #     when 3..4
    #       'orange'
    #     when 5..6
    #       'green'
    #     when 6..7
    #       'purple'
    #     else 
    #       'blue' # default color
    #     end
    #   end
end

app/helpers/sessions_helper.rb
module SessionsHelper
    # def log_in(user)
    #   session[:user_id] = user.id
    # end
    def current_user
      @current_user ||= User.find_by(id: session[:user_id])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppName</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>

  
</html>

app/views/tasks/_form.html.erb
<%= form_for @task do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :due_date %><br>
    <%= f.date_field :due_date, min: Date.today.to_s %>
  </div>

  <div class="field">
  <%= f.label :difficulty, "Priority" %><br>
  <%= f.select :difficulty, Task.difficulties.keys.map { |difficulty| [difficulty.humanize, difficulty] }, {}, { class: 'select-class' } %>
  </div>

  <div class="field">
    <%= f.label :estimate, 'Estimated time range' %>
    <%= f.number_field :estimate, value: @task.estimate || 0, required: true, min: 0, class: 'form-control' %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task, class: 'button' %> |
<%= link_to 'Back', tasks_path, class: 'button' %>

app/views/tasks/index.html.erb
<h1>Incoming Tasks...</h1>

<body>
    <div>
        <p class="centered">Try to click "Due Date" or "Sugessted Start Date" to quickly sort your tasks...</p>
      
    </div>
</body>    

<table>
  <thead>
    <tr>
      <th class="centered">Name</th>
      <th class="centered">
        <%= link_to 'Due Date', tasks_path(sort: 'due_date', direction: params[:direction] == 'asc' ? 'desc' : 'asc'), style: 'color: white;' %>
      </th>
      <th class="centered">Priority</th>
      <th class="centered">
        <%= link_to 'Suggested Start Date', tasks_path(sort: 'start_time', direction: params[:direction] == 'asc' ? 'desc' : 'asc'), style: 'color: white;' %>
      </th>
      <th class="centered">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td class="centered"><%= task.name %></td>
        <td class="centered"><%= task.due_date %></td>
        <td class="centered"><%= task.difficulty %></td>
        <td class="centered"><%= task.start_time %></td>
        <td class="centered">
          <%= link_to 'Show', task_path(task), class: 'button' %> |
          <%= link_to 'Edit', edit_task_path(task), class: 'button' %> |
          <%= link_to 'Delete', manual_delete_task_path(task), class: 'button' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class='centered'>
  <%= link_to 'New Task', new_task_path, class: 'button' %>
  <%= link_to 'Log Out', login_path, class: 'button' %>
</div>

app/views/tasks/new.html.erb
<h1>Create a New Task</h1>

<%= form_for @task do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :due_date, "Due date" %>
    <%= f.date_field :due_date, min: Date.today.to_s %>
  </div>

  <div class="field">
    <%= f.label :difficulty, "Priority" %>
    <%= f.select :difficulty, Task.difficulties.keys.map { |difficulty| [difficulty.humanize, difficulty] }, {}, { class: 'select-class' } %>  
  </div>

  <div class="field">
    <%= f.label :estimate, "Estimate time range(in hours)" %>
    <%= f.number_field :estimate, value: @task.estimate || 0, required: true, min: 0, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<div class="back-link">
  <%= link_to 'Back', tasks_path, class: 'button' %>
</div>

app/views/tasks/show.html.erb
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f0f0f0;
      margin: 0;
      padding: 20px;
      display: flex;
      flex-direction: column;
      align-items: center;
      text-align: center;
    }

    h1 {
      color: lightblue;
    }

    p {
      margin-bottom: 10px;
    }

    .button {
      background-color: #008CBA;
      color: white;
      padding: 10px 15px;
      text-decoration: none;
      display: inline-block;
      font-size: 16px;
      margin: 4px 2px;
      cursor: pointer;
      border-radius: 4px;
    }
  </style>
</head>
<body>
  <h1>Explore Your Task Details...</h1>

  <p>
    <strong>Name:</strong>
    <%= @task.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @task.description %>
  </p>

  <p>
    <strong>Due Date:</strong>
    <%= @task.due_date %>
  </p>

  <p>
    <strong>Priority:</strong>
    <%= @task.difficulty %>
  </p>

  <p>
    <strong>Estimated Time Range(Hours):</strong>
    <%= @task.estimate %>
  </p>

  <p>
    <strong>Suggested Start Date:</strong>
    <%= @task.start_time %>
  </p>

  <div>
    <%= link_to 'Edit', edit_task_path(@task), class: 'button' %> |
    <%= link_to 'Back', tasks_path, class: 'button' %>
  </div>
</body>
</html>

app/views/users/new.html.erb
<div style="width: 100%; text-align: right;">
  <%= link_to 'Log In', login_path, class: 'button' %>
</div>

<h1>Sign Up</h1>
<%= form_with(model: @user, url: users_path, local: true) do |form| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
            <ul>
                <% @user.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= form.label :email %><br>
        <%= form.email_field :email %>
    </div>

    <div class="field">
        <%= form.label :password %>
        <%= form.password_field :password, autocomplete: "new-password" %>
    </div>

    <div class="field">
        <%= form.label :password_confirmation, "Confirm Password" %>
        <%= form.password_field :password_confirmation, autocomplete: "new-password" %>
    </div>

    <div class="actions">
        <%= form.submit "Sign up" %>
    </div>
<% end %>